spring:
  application:
    name: oauth-server

server:
  port: 9000

logging:
  level:
    org.springframework.security: TRACE

application:
  client:
    uri: ${HOST_CLIENT:http://127.0.0.1:4200}
    path-logout: ${PATH_LOGOUT:/app/logout}
    path-redirectUri: ${PATH_REDIRECT_URI:/app/authorize}
